"""Data models for the trading bot."""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, Dict, List
from enum import Enum


class OrderSide(Enum):
    """Order side enumeration."""
    BUY = "buy"
    SELL = "sell"


class OrderStatus(Enum):
    """Order status enumeration."""
    PENDING = "pending"
    FILLED = "filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"


@dataclass
class PriceData:
    """Price data from exchange."""
    exchange: str
    symbol: str
    price: float
    volume: float
    timestamp: datetime
    
    
@dataclass
class AggregatedPrice:
    """Aggregated price data across exchanges."""
    symbol: str
    vwap: float
    prices: Dict[str, float]
    volumes: Dict[str, float]
    timestamp: datetime
    

@dataclass
class TradingSignal:
    """Trading signal generated by the signal generator."""
    symbol: str
    side: OrderSide
    edge: float
    probability: float
    kalshi_price: float
    fair_value: float
    timestamp: datetime
    confidence: float
    

@dataclass
class Position:
    """Current position information."""
    symbol: str
    quantity: int
    entry_price: float
    current_price: float
    pnl: float
    timestamp: datetime
    

@dataclass
class RiskMetrics:
    """Risk metrics for position sizing."""
    kelly_size: int
    max_position: int
    current_exposure: float
    daily_pnl: float
    remaining_capacity: float
    

@dataclass
class Order:
    """Order information."""
    order_id: str
    symbol: str
    side: OrderSide
    quantity: int
    price: float
    status: OrderStatus
    timestamp: datetime
    filled_quantity: int = 0
    

@dataclass
class MarketData:
    """Kalshi market data."""
    market_id: str
    symbol: str
    yes_bid: float
    yes_ask: float
    no_bid: float
    no_ask: float
    volume: int
    timestamp: datetime
    

@dataclass
class VolatilityData:
    """Volatility data for probability calculations."""
    symbol: str
    historical_vol: float
    implied_vol: Optional[float]
    std_dev: float
    timestamp: datetime
